[build]
  command = "npm run build"
  publish = "dist"  # or the directory where your build artifacts are generated

[dev]
  command = "npm run dev"
  port = 3000  # or the port number your dev server is running on

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-deploy-core"
